sudo: required
services:
  - docker

before_install:
  - docker build -t binuraen/docker-react-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true binuraen/docker-react-demo npm run test

language: generic 